### ISSUE TITLE
Need more poetry!

### ISSUE THREAD

**Issue by Kristusha100** [Kristusha100/git-sandbox#1]
Would be nice to have some poetic lines in the repo. It's too boring now.

**Comment by gbezyuk** [comment]
I guess I could help with that!

**Comment by Kristusha100** [comment]
@gbezyuk great let's do it!

**Comment by Kristusha100** [comment]
Enough with poetry!

**Comment by gbezyuk** [comment]
...but I have more...

**Comment by Kristusha100** [comment]
NOPE IT'S DONE LET'S MOVE ON!
